### ISSUE TITLE
Feature request: version flag or command for all indicator* CLI tools

### ISSUE THREAD

**Issue by sunjayBhatia** [pivotal/monitoring-indicator-protocol#3]
When using the various `indicator*` tools, I would like a `--version` flag or `version` command that gives me the version of the CLI I am using. Often we may have to re-download the tool we are using because we don't know what version the one on our workstation is after we rename it to a generic name.

**Note**: this is applicable to https://github.com/pivotal/healthwatch-indicator-dashboard-releases as well

**Comment by jpmcb** [comment]
Thanks for this! We put a story in our backlog - https://www.pivotaltracker.com/story/show/169763175

**Comment by vreynolds** [comment]
@sunjayBhatia the `version` flag is available beginning with release [0.9.1](https://github.com/pivotal/monitoring-indicator-protocol/releases/tag/v0.9.1)
